//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podbor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Podbor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AlertProvader {
            get {
                object obj = ResourceManager.GetObject("AlertProvader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BlackHideLottie {
            get {
                object obj = ResourceManager.GetObject("BlackHideLottie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] debtors_credits {
            get {
                object obj = ResourceManager.GetObject("debtors_credits", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EmailBlackLottie {
            get {
                object obj = ResourceManager.GetObject("EmailBlackLottie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EmailLottie {
            get {
                object obj = ResourceManager.GetObject("EmailLottie", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ErrorProvaider {
            get {
                object obj = ResourceManager.GetObject("ErrorProvaider", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InfoProvader {
            get {
                object obj = ResourceManager.GetObject("InfoProvader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading1 {
            get {
                object obj = ResourceManager.GetObject("Loading1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading2 {
            get {
                object obj = ResourceManager.GetObject("Loading2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading3 {
            get {
                object obj = ResourceManager.GetObject("Loading3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading4 {
            get {
                object obj = ResourceManager.GetObject("Loading4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Loading5 {
            get {
                object obj = ResourceManager.GetObject("Loading5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mailActiv {
            get {
                object obj = ResourceManager.GetObject("mailActiv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mailNewPass {
            get {
                object obj = ResourceManager.GetObject("mailNewPass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] non_group {
            get {
                object obj = ResourceManager.GetObject("non_group", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NoNetworking {
            get {
                object obj = ResourceManager.GetObject("NoNetworking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RebasePasswordWhite {
            get {
                object obj = ResourceManager.GetObject("RebasePasswordWhite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RightLottie {
            get {
                object obj = ResourceManager.GetObject("RightLottie", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] account
        {
            get
            {
                object obj = ResourceManager.GetObject("account", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] credit
        {
            get
            {
                object obj = ResourceManager.GetObject("credit", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] credit_test
        {
            get
            {
                object obj = ResourceManager.GetObject("credit_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] credit_no_active
        {
            get
            {
                object obj = ResourceManager.GetObject("credit_no_active", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] credit_add
        {
            get
            {
                object obj = ResourceManager.GetObject("credit_add", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] finance
        {
            get
            {
                object obj = ResourceManager.GetObject("finance", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] account_admin
        {
            get
            {
                object obj = ResourceManager.GetObject("account_admin", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] time
        {
            get
            {
                object obj = ResourceManager.GetObject("time", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] planing
        {
            get
            {
                object obj = ResourceManager.GetObject("planing", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WhiteHideLottie {
            get {
                object obj = ResourceManager.GetObject("WhiteHideLottie", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mailGoodRegistration {
            get {
                object obj = ResourceManager.GetObject("mailGoodRegistration", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] support {
            get {
                object obj = ResourceManager.GetObject("support", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] registration {
            get {
                object obj = ResourceManager.GetObject("registration", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] autorizate {
            get {
                object obj = ResourceManager.GetObject("autorizate", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] future_debtors_credit {
            get {
                object obj = ResourceManager.GetObject("future_debtors_credit", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] support_in {
            get {
                object obj = ResourceManager.GetObject("support_in", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
		/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] support_out {
            get {
                object obj = ResourceManager.GetObject("support_out", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
				/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] delete_support {
            get {
                object obj = ResourceManager.GetObject("delete_support", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
						/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] assets {
            get {
                object obj = ResourceManager.GetObject("assets", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
								/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pasive {
            get {
                object obj = ResourceManager.GetObject("pasive", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
										/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] finance_group {
            get {
                object obj = ResourceManager.GetObject("finance_group", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
												/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] add_file {
            get {
                object obj = ResourceManager.GetObject("add_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
												/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Check {
            get {
                object obj = ResourceManager.GetObject("Check", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
														/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] stability {
            get {
                object obj = ResourceManager.GetObject("stability", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
														/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] no_stability {
            get {
                object obj = ResourceManager.GetObject("no_stability", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] delete_cash {
            get {
                object obj = ResourceManager.GetObject("delete_cash", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mailSupportAnswer {
            get {
                object obj = ResourceManager.GetObject("mailSupportAnswer", resourceCulture);
                return ((byte[])(obj));
            }
        }
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] mailSupport {
            get {
                object obj = ResourceManager.GetObject("mailSupport", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																			/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] in_cash {
            get {
                object obj = ResourceManager.GetObject("in_cash", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] translete_cash {
            get {
                object obj = ResourceManager.GetObject("translete_cash", resourceCulture);
                return ((byte[])(obj));
            }
        }
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] pay {
            get {
                object obj = ResourceManager.GetObject("pay", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																					/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] barter {
            get {
                object obj = ResourceManager.GetObject("barter", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] no_debtor {
            get {
                object obj = ResourceManager.GetObject("no_debtor", resourceCulture);
                return ((byte[])(obj));
            }
        }
																	/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] debtor {
            get {
                object obj = ResourceManager.GetObject("debtor", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																			/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] add_time {
            get {
                object obj = ResourceManager.GetObject("add_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
		
																			/// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] delete_time {
            get {
                object obj = ResourceManager.GetObject("delete_time", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
